name: Build, Test, Push Docker Image, and Deploy to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-test  # Run only if build-test succeeds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest

  deploy-to-minikube:
    runs-on: ubuntu-latest
    needs: build-and-push  # Run only if build-and-push succeeds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@v0.0.14

      - name: Deploy to Minikube
        run: |
          kubectl create deployment calculator-app --image=${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest || kubectl set image deployment/my-python-app my-python-app=${{ secrets.DOCKERHUB_USERNAME }}/my-python-app:latest
          kubectl expose deployment calculator-app --type=NodePort --port=5000 || true
          kubectl get pods -o wide

      - name: Wait for Pod to Be Ready
        run: kubectl wait --for=condition=ready pod -l app=calculator-app --timeout=60s

      - name: Verify Service
        run: kubectl get svc calculator-app

      - name: Get Minikube Service URL
        run: |
          echo "Fetching Minikube service URL..."
          minikube service calculator-app --url
