name: Build, Test, Push Docker Image, and Deploy to Web Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  build-and-push:
    runs-on: ubuntu-latest
    needs: build-test  # Run only if build-test succeeds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest

  deploy-to-webserver:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Web Server
        env:
          PRIVATE_KEY: ${{ secrets.WEBSERVER_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.WEBSERVER_HOST }}
          USER: ${{ secrets.WEBSERVER_USER }}
          
        run: |
          echo "${{ secrets.WEBSERVER_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest

            # Stop and remove the existing container if running
            docker rm -f calculator-app || true

            # Run the container on the web server
            docker run -d -p 80:5000 --name calculator-app ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest
          EOF
